nama = input("Masukkan nama Anda: ")
umur = int(input("Masukkan umur Anda: "))
Universitas = input("Masukkan nama universitas Anda: ")
Fakultas = input("Masukkan nama fakultas Anda: ")
Prodi = input("Masukkan nama prodi Anda: ")
print("Halo, nama saya", nama)
print("Saya berumur", umur, "tahun")
print("Saya kuliah di", Universitas)
print("Fakultas saya adalah", Fakultas)
print("Prodi saya adalah", Prodi)
print("Saya sangat senang belajar Python!")
print("========================================")
print("Terima kasih telah mengisi data diri Anda, " + nama + "!")
print("========================================")
print("========================================")
print("Data diri Anda telah berhasil disimpan.")
print("========================================")
print("========================================")
print("Semoga hari Anda menyenangkan, " + nama + "!")
print("========================================")
print("========================================")
print("Sampai jumpa lagi, " + nama + "!")
print("========================================")